npmRegistryServer: "https://registry.npm.taobao.org"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.js
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.js
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.js
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-stage.js
    spec: "@yarnpkg/plugin-stage"

pnpMode: loose

yarnPath: .yarn/releases/yarn-2.0.0-rc.33.js
