name: NPM Publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build Cache
        id: build-cache
        uses: actions/cache@v2
        with:
          path: .yarn
          key: ${{ runner.os }}-build-cache

      - run: yarn
      - run: yarn build
      - name: Publish NPM
        run: |
          echo '//npm.pkg.github.com:_authToken=${GITHUB_TOKEN}'>.npmrc
          yarn lerna publish from-git --yes --registry "https://npm.pkg.github.com/wenerme"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
